---
deployment:
  tasks:
    - export DEPLOYPATH=/home/philpkhg/public_html_centennial.phillykappas.org/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R styles $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
