---
deployment:
  tasks:
    - export DEPLOYPATH=/home/philpkhg/public_html_centennial.phillykappas.org/
    - /bin/cp comingsoon.html $DEPLOYPATH
    - /bin/cp /styles/style.css $DEPLOYPATH
    - /bin/cp /images/* $DEPLOYPATH
